// Auto-generated types from Supabase (this would normally be generated by Supabase CLI)
// For now, we'll create a compatible structure manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      spaces: {
        Row: {
          id: string
          user_id: string
          name: string
          color: string
          description: string | null
          created_at: string
          updated_at: string
          is_archived: boolean
          sort_order: number
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          color?: string
          description?: string | null
          created_at?: string
          updated_at?: string
          is_archived?: boolean
          sort_order?: number
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          color?: string
          description?: string | null
          created_at?: string
          updated_at?: string
          is_archived?: boolean
          sort_order?: number
        }
      }
      items: {
        Row: {
          id: string
          user_id: string
          space_id: string | null
          title: string
          url: string | null
          content_type: Database['public']['Enums']['content_type']
          content: string | null
          description: string | null
          thumbnail_url: string | null
          raw_text: string | null
          created_at: string
          updated_at: string
          archived_at: string | null
          is_archived: boolean
          is_favorite: boolean
          search_vector: unknown
        }
        Insert: {
          id?: string
          user_id: string
          space_id?: string | null
          title: string
          url?: string | null
          content_type?: Database['public']['Enums']['content_type']
          content?: string | null
          description?: string | null
          thumbnail_url?: string | null
          raw_text?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
          is_archived?: boolean
          is_favorite?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          space_id?: string | null
          title?: string
          url?: string | null
          content_type?: Database['public']['Enums']['content_type']
          content?: string | null
          description?: string | null
          thumbnail_url?: string | null
          raw_text?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
          is_archived?: boolean
          is_favorite?: boolean
        }
      }
      tags: {
        Row: {
          id: string
          user_id: string
          name: string
          color: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          color?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          color?: string | null
          created_at?: string
        }
      }
      items_tags: {
        Row: {
          item_id: string
          tag_id: string
          created_at: string
        }
        Insert: {
          item_id: string
          tag_id: string
          created_at?: string
        }
        Update: {
          item_id?: string
          tag_id?: string
          created_at?: string
        }
      }
      item_metadata: {
        Row: {
          id: string
          item_id: string
          author: string | null
          domain: string | null
          duration: number | null
          file_size: number | null
          page_count: number | null
          username: string | null
          likes: number | null
          replies: number | null
          retweets: number | null
          views: number | null
          price: number | null
          rating: number | null
          reviews: number | null
          in_stock: boolean | null
          stars: number | null
          forks: number | null
          language: string | null
          citations: number | null
          published_date: string | null
          journal: string | null
          extra_data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          item_id: string
          author?: string | null
          domain?: string | null
          duration?: number | null
          file_size?: number | null
          page_count?: number | null
          username?: string | null
          likes?: number | null
          replies?: number | null
          retweets?: number | null
          views?: number | null
          price?: number | null
          rating?: number | null
          reviews?: number | null
          in_stock?: boolean | null
          stars?: number | null
          forks?: number | null
          language?: string | null
          citations?: number | null
          published_date?: string | null
          journal?: string | null
          extra_data?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          item_id?: string
          author?: string | null
          domain?: string | null
          duration?: number | null
          file_size?: number | null
          page_count?: number | null
          username?: string | null
          likes?: number | null
          replies?: number | null
          retweets?: number | null
          views?: number | null
          price?: number | null
          rating?: number | null
          reviews?: number | null
          in_stock?: boolean | null
          stars?: number | null
          forks?: number | null
          language?: string | null
          citations?: number | null
          published_date?: string | null
          journal?: string | null
          extra_data?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      content_type: 
        | 'x' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'reddit' | 'facebook'
        | 'github' | 'gitlab' | 'codepen' | 'stackoverflow' | 'devto' | 'npm' | 'documentation'
        | 'article' | 'pdf' | 'image' | 'video' | 'audio' | 'presentation'
        | 'product' | 'amazon' | 'etsy' | 'app'
        | 'wikipedia' | 'paper' | 'book' | 'course'
        | 'note' | 'bookmark' | 'recipe' | 'location'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}